armstizzy-picoctf@webshell:~$ wget https://artifacts.picoctf.net/c/38/fixme1.py
--2023-03-08 19:56:17--  https://artifacts.picoctf.net/c/38/fixme1.py
Resolving artifacts.picoctf.net (artifacts.picoctf.net)... 108.156.172.74, 108.156.172.120, 108.156.172.6, ...
Connecting to artifacts.picoctf.net (artifacts.picoctf.net)|108.156.172.74|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 837 [application/octet-stream]
Saving to: 'fixme1.py'

fixme1.py                                                           100%[=================================================================================================================================================================>]     837  --.-KB/s    in 0s      

2023-03-08 19:56:18 (253 MB/s) - 'fixme1.py' saved [837/837]
armstizzy-picoctf@webshell:~$ python3 fixme1.py 
  File "/home/armstizzy-picoctf/fixme1.py", line 20
    print('That is correct! Here\'s your flag: ' + flag)
IndentationError: unexpected indent
armstizzy-picoctf@webshell:~$ python3 fixme1.py 
That is correct! Here's your flag: picoCTF{1nd3nt1ty_cr1515_09ee727a}
